repositories:
  remote:
   - http://repo1.maven.org/maven2
  release_to:
    url: http://repo.fire.dse.vic.gov.au/content/repositories/releases/
    username: upload

artifacts:
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  joda_time: joda-time:joda-time:jar:1.6
